Repository apache/maven-scm, pull requests merged in 2025-08, with the labels that each got.

#1280 Git: Observe interactive flag
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/GitExeScmProvider.java
Labels: enhancement

#1287 Replace unintended octal constants
  maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/info/InfoCommandTckTest.java
Labels: skip-changelog

#1284 Use Files.lines
  maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svn-commons/src/main/java/org/apache/maven/scm/provider/svn/SvnConfigFileReader.java
Labels: maintenance, skip-changelog

#1290 Remove redundant code
  maven-scm-api/src/main/java/org/apache/maven/scm/ChangeSet.java
  maven-scm-api/src/main/java/org/apache/maven/scm/repository/ScmRepository.java
  maven-scm-api/src/test/java/org/apache/maven/scm/ScmFileSetTest.java
  maven-scm-client/src/main/java/org/apache/maven/scm/client/cli/MavenScmCli.java
  maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/AddMojo.java
  maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/ChangeLogMojo.java
  maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/ValidateMojo.java
  maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/command/add/HgAddConsumer.java
  maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/command/remove/HgRemoveConsumer.java
  maven-scm-providers/maven-scm-provider-local/src/test/java/org/apache/maven/scm/provider/local/command/update/LocalUpdateCommandTckTest.java
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-git-commons/src/main/java/org/apache/maven/scm/provider/git/command/diff/GitDiffConsumer.java
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/checkout/GitCheckOutCommand.java
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/remove/GitRemoveConsumer.java
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/update/GitUpdateCommand.java
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/test/java/org/apache/maven/scm/provider/git/gitexe/command/remove/GitRemoveConsumerTest.java
  maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/info/SvnInfoCommand.java
  maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svnexe/src/main/java/org/apache/maven/scm/provider/svn/svnexe/command/mkdir/SvnMkdirConsumer.java
  maven-scm-test/src/main/java/org/apache/maven/scm/provider/ScmProviderStub.java
  maven-scm-test/src/main/java/org/apache/maven/scm/tck/command/checkout/CheckOutCommandTckTest.java
Labels: skip-changelog

#1300 Use Charset to remove formal need for RuntimeException
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/status/GitStatusConsumer.java
Labels: skip-changelog

#1303 Prefer https
  maven-scm-providers/maven-scm-providers-git/maven-scm-provider-gitexe/src/main/java/org/apache/maven/scm/provider/git/gitexe/command/blame/GitBlameConsumer.java
  maven-scm-test/src/main/java/org/apache/maven/scm/manager/ScmManagerStub.java
  maven-scm-test/src/main/java/org/apache/maven/scm/provider/ScmProviderRepositoryStub.java
  maven-scm-test/src/main/java/org/apache/maven/scm/provider/ScmProviderStub.java
  maven-scm-test/src/main/java/org/apache/maven/scm/repository/ScmRepositoryStub.java
  src/site/site.xml
  src/site/xdoc/download.xml.vm
Labels: documentation, skip-changelog

#1302 Update Mercurial URL
  maven-scm-providers/maven-scm-provider-hg/src/main/java/org/apache/maven/scm/provider/hg/HgScmProvider.java
Labels: skip-changelog

#1306 Throw is enough
  maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/CheckLocalModificationsMojo.java
  maven-scm-plugin/src/main/java/org/apache/maven/scm/plugin/TagMojo.java
Labels: maintenance
